### ISSUE TITLE
大佬看到你在iOSre发的帖子了 请教一个问题

### ISSUE THREAD

**Issue by WhoJave** [yuzhouheike/HookZz-Learn#1]
http://iosre.com/t/llvm-profile-error-default-profraw/11828/25
这个里面的那个qqauthlogin这类的玩意儿是 自己写的打包成动态库的么 用的bmob的api的 没找到这种动态库的 这种自己要怎么整的

**Comment by yuzhouheike** [comment]
所有导致闪退的(exit)函数都会报这个日志。所以你要做的不是去搜这个日志，而是去看看函数调用栈，找到这个日志之前的调用的那些函数，然后HooK导致闪退的那个函数一般都是exit函数导致的这个日志，
